"use client";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { usePathname } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

const metadata = {
  title: "Sheikh Majid",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const pathname = usePathname();
  console.log(pathname);

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="first">
          <div>
            <ul>
              <li className="nav">Navbar</li>
            </ul>
          </div>
          <div>
            <ul className="second">
              {pathname !== "/signup" ? (
                <>
                  <li>
                    <Link href="/login" className="third">
                      login
                    </Link>
                  </li>
                  <li>
                    <Link href="/signup" className="third">
                      Signup
                    </Link>
                  </li>
                  <li>
                    <Link href="/about" className="third">
                      About
                    </Link>
                  </li>
                </>
              ) : (
                <>
                  <li>
                    <Link href="/logout" className="third">
                      Logout
                    </Link>
                  </li>
                  <li>
                    <Link href="/studentlist" className="third">
                      StudentList
                    </Link>
                  </li>
                </>
              )}
            </ul>
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
