import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className=" bg-slate-800 text-white text-2xl flex justify-center mt-4" >
        <h1>Navbar</h1>
        {children}
        <h1>Footer First</h1>
      </body>
    </html>
  );
}
